### ISSUE TITLE
Interesting...

### ISSUE THREAD

**Issue by prologic** [cslarsen/lyn#1]
Could you elaborate on more practical use-cases for this? :) I get what a JIT is and all and whilst a trivial example of a function that returns `123` is interesting and all; what other practical uses-cases can one expect from Lyn? :) -- What are your own plans/goals for this?

**Comment by cslarsen** [comment]
I heard this story about a researcher who wanted to make a PostScript driver, or something to that effect. After a long time, he showed his colleagues a single sheet of paper with a large "A" printed on it. They laughed at him, because he had spent so much time and had only managed to print one letter. :-)

Well, I just wanted to play with GNU Lightning in Python, but couldn't find any bindings. So I made this. GNU Lightning is used for JIT-compilation in GNU Smalltalk, Racket and CLISP. And probably in many other projects.

I don't have any particular grand plan for this work, yet. But I'd like to write a feature-complete binding to GNU Lightning, and we'll see what, if anything, comes out of it. I'm pretty sure a lot of people will want to use Lyn, though.

Cheers!

**Comment by prologic** [comment]
Cool thanks for the response! :) I'm sure I'll want to play around with it myself! THanks for writing this and publishing it!

**Comment by cslarsen** [comment]
Thanks for leaving a comment! Cheers

**Comment by acekingke** [comment]
![image](https://cloud.githubusercontent.com/assets/7586502/11869323/f0f9b91c-a4f9-11e5-84ff-35fa15b0a95f.png)

**Comment by cslarsen** [comment]
Please file a separate issue and add your Python version.
